image: Visual Studio 2019
artifacts:
  - path: '**\jsreport.AspNetCore*.nupkg'
    name: nuget
    type: NuGetPackage
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
build:
  project: jsreport.AspNetCore.sln
before_build:
  - cmd: dotnet restore
deploy:
  provider: NuGet
  api_key:
    secure: 8YEU/HfxJmYnx+WcWGi7Lay3uoTDIfDh3R2CdEhDsUZpoDmqK9g4IP1xq+NnwDLM
  on:
    appveyor_repo_tag: true
test_script:
- cd jsreport.AspNetCore.Test
- dotnet test    